# SELECT o.ANIMAL_ID
#     ,o.NAME 
# FROM ANIMAL_OUTS o LEFT OUTER JOIN
#     ANIMAL_INS i
# ON o.ANIMAL_ID = i.ANIMAL_ID;
# WHERE i.ANIMAL_ID IS NULL
# ORDER BY ANIMAL_ID


SELECT ANIMAL_ID,
       NAME 
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (
                    SELECT ANIMAL_ID
                        FROM ANIMAL_INS)
ORDER BY ANIMAL_ID