-- 코드를 입력하세요
# "세단" 또는 "SUV" 중 2022년 11-1 ~ 11-30까지 대여 가능하고, 대여 금액이 50만원 이상, 200만원 미만인 자동차
# 대여 가능한 CAR_ID 구하기


# SELECT 
#     CC.CAR_ID,
#     CC.CAR_TYPE,
#     DAILY_FEE * 30 AS FEE
# FROM
#     CAR_RENTAL_COMPANY_CAR CC,
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY RH,
#     CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
# WHERE CC.CAR_ID = RH.CAR_ID
# AND CC.CAR_TYPE = DP.CAR_TYPE
# AND CC.CAR_TYPE IN("세단", "SUV")    
# ORDER BY 3 DESC, 2, 1 DESC


# 사용 가능한 차량
WITH CAN_USE_CAR AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
        GROUP BY 1
        HAVING MAX(END_DATE) < '2022-11-01'
        # WHERE START_DATE NOT BETWEEN '2022-11-01' AND '2022-11-30'
        # OR END_DATE NOT BETWEEN '2022-11-01' AND '2022-11-30'
    )

), DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ("SUV", "세단")
    AND DURATION_TYPE LIKE "30%"
)

SELECT 
    CC.CAR_ID,
    CC.CAR_TYPE,
    ROUND((DAILY_FEE * ((100 - DI.DISCOUNT_RATE) / 100)) * 30) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR CC,
    DISCOUNT DI,
    CAN_USE_CAR UC
WHERE CC.CAR_TYPE IN("세단", "SUV")
AND CC.CAR_ID = UC.CAR_ID
AND CC.CAR_TYPE = DI.CAR_TYPE
AND ROUND((DAILY_FEE * ((100 - DI.DISCOUNT_RATE) / 100)) * 30) >= 500000
AND ROUND((DAILY_FEE * ((100 - DI.DISCOUNT_RATE) / 100)) * 30) < 2000000
ORDER BY 3 DESC, 2, 1 DESC