SELECT CONCAT("/home/grep/src/", GB.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILEPATH
FROM USED_GOODS_BOARD GB,
        USED_GOODS_FILE GF
WHERE 
    VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
AND 
    GB.BOARD_ID = GF.BOARD_ID
ORDER BY FILE_ID DESC

