WITH RECURSIVE tb1 AS (
    SELECT 0 AS HOUR
    FROM dual
    UNION ALL
    SELECT HOUR + 1 FROM tb1 
    WHERE HOUR < 23
    ), tb2 AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(distinct(ANIMAL_ID)) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY 1
    )
    
SELECT tb1.HOUR AS HOUR, IF(ISNULL(COUNT), 0, COUNT) AS COUNT
FROM tb1 LEFT OUTER JOIN tb2
ON tb1.HOUR = tb2.HOUR

    