SELECT 
    USER_ID,
    NICKNAME,
    CONCAT_WS(" ", CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS 전체주소,
    CONCAT_WS("-", MID(TLNO, 1, 3), MID(TLNO, 4, 4), MID(TLNO, 8, 4)) AS 전화번호
FROM 
    USED_GOODS_BOARD GB,
    USED_GOODS_USER GU
WHERE GB.WRITER_ID = GU.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY 1 DESC