-- 코드를 입력하세요
SELECT CATEGORY,
        sum(SALES) AS TOTAL_SALES
    FROM BOOK b, BOOK_SALES s
   WHERE b.BOOK_ID = s.BOOK_ID
   AND LEFT(SALES_DATE, 7) = '2022-01'
   GROUP BY CATEGORY
   ORDER BY CATEGORY