SELECT 
    TITLE,
    GB.BOARD_ID,
    REPLY_ID,
    GR.WRITER_ID,
    GR.CONTENTS,
    LEFT(GR.CREATED_DATE,10) CREATED_DATE
FROM 
    USED_GOODS_BOARD GB,
    USED_GOODS_REPLY GR
WHERE GB.BOARD_ID = GR.BOARD_ID
AND GB.CREATED_DATE LIKE '2022-10%'
ORDER BY 6, 1