# (출력)'트럭' 대여기록별로 대여금액을 구하여 대여 기록 ID와 대여 금액리스트
# (정렬) '금액' 내림차순, 대여 기록 ID 내림차순

WITH RENTAL_PERIOD AS (
    SELECT
    HISTORY_ID,
    CAR_ID,
    START_DATE,
    END_DATE,
    DATEDIFF(END_DATE, START_DATE) +1 AS DATEDIFF, 
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) +1 >= 90
        THEN 90
        WHEN DATEDIFF(END_DATE, START_DATE) +1 >= 30
        THEN 30
        WHEN DATEDIFF(END_DATE, START_DATE) +1 >= 7
        THEN 7
        ELSE 0
        END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)


SELECT 
# RP.*,CC.*, DP.*,
DISTINCT(HISTORY_ID),
ROUND((DAILY_FEE - (DAILY_FEE * IF(DURATION = 0, 0, DISCOUNT_RATE) / 100)) * DATEDIFF) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR CC,
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP,
    RENTAL_PERIOD RP
WHERE DP.CAR_TYPE = CC.CAR_TYPE
AND CC.CAR_ID = RP.CAR_ID
AND CC.CAR_TYPE = '트럭'
AND RP.DURATION IN (0, CAST(DP.DURATION_TYPE AS UNSIGNED))
ORDER BY 2 DESC, 1 DESC
# # # GROUP BY 1