-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT p, FOOD_ORDER o
WHERE p.PRODUCT_ID = o.PRODUCT_ID
AND PRODUCE_DATE LIKE '2022-05%'
GROUP BY o.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC

# 생산일자가 2022년 5월인
# 식품 ID, 식품이름, 총매출 조회
# 총매출 기준 DESC, 식품 ID ASC
