-- 코드를 입력하세요
WITH HEAVY_USERS AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING count(*) >= 2
)

SELECT 
    PL.ID, PL.NAME, PL.HOST_ID 
FROM 
    HEAVY_USERS HU,
    PLACES PL
WHERE HU.HOST_ID = PL.HOST_ID
AND HU.HOST_ID IN (PL.HOST_ID)
ORDER BY 1