

# '세단' 자동차들 중 10월에 대여를 시작한 기록이 있는 자동차 ID 리스트
# 중복 X, 자동차 ID 기준 내림차순

SELECT 
    CC.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR CC JOIN  
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON CC.CAR_ID = RH.CAR_ID
WHERE CAR_TYPE = '세단'
AND START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
GROUP BY CC.CAR_ID
ORDER BY 1 DESC
