SELECT 
        CAR_TYPE,
        COUNT(CAR_ID) AS CARS
        # OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE REGEXP_LIKE(OPTIONS, '통풍시트') or
REGEXP_LIKE(OPTIONS, '열선시트') or
REGEXP_LIKE(OPTIONS, '가죽시트')
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC