SELECT 
    WRITER_ID AS USER_ID
    ,NICKNAME
    ,SUM(PRICE) AS TOTAL_SALES
FROM 
    USED_GOODS_BOARD GB,
    USED_GOODS_USER GU
WHERE GB.WRITER_ID = GU.USER_ID
AND STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3